export default {
  REQUESTED_USERS: 'REQUESTED_USERS',
  NEW_USER_MODAL_OPEN: 'NEW_USER_MODAL_OPEN',
  SORT_USERS_BY: 'SORT_USERS_BY',
  DISPLAY_USERS_PER_PAGE: 'DISPLAY_USERS_PER_PAGE',
  EDIT_USER_MODAL_OPEN: 'EDIT_USER_MODAL_OPEN',
  EDIT_USER_DATA: 'EDIT_USER_DATA',
  EDIT_USER_SUBMIT: 'EDIT_USER_SUBMIT',
  EDIT_USER_DATA_CLEAR: 'EDIT_USER_DATA_CLEAR',
  DELETE_USER_MODAL_OPEN: 'DELETE_USER_MODAL_OPEN',
}