export default {
  REQUESTED_USERS: 'REQUESTED_USERS',
  REQUEST_USERS_ERROR: 'REQUEST_USERS_ERROR',
  NEW_USER_MODAL_OPEN: 'NEW_USER_MODAL_OPEN',
  SORT_USERS_BY: 'SORT_USERS_BY',
  DISPLAY_USERS_PER_PAGE: 'DISPLAY_USERS_PER_PAGE',
  EDIT_USER_MODAL_OPEN: 'EDIT_USER_MODAL_OPEN',
  DELETE_USER_MODAL_OPEN: 'DELETE_USER_MODAL_OPEN',
}