export default {
  REQUEST_USERS: 'REQUEST_USERS',
  CREATE_USER_MODAL_OPEN: 'CREATE_USER_MODAL_OPEN',
  CREATE_USER_DATA_CLEAR: 'CREATE_USER_DATA_CLEAR',
  SORT_USERS_BY: 'SORT_USERS_BY',
  DISPLAY_USERS_PER_PAGE: 'DISPLAY_USERS_PER_PAGE',
  EDIT_USER_MODAL_OPEN: 'EDIT_USER_MODAL_OPEN',
  EDIT_USER_DATA: 'EDIT_USER_DATA',
  EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
  EDIT_USER_DATA_CLEAR: 'EDIT_USER_DATA_CLEAR',
  DELETE_USER_MODAL_OPEN: 'DELETE_USER_MODAL_OPEN',
}