export default {
  REQUEST_USER_FILES: 'REQUEST_USER_FILES',
  CREATE_FILE_MODAL_OPEN: 'CREATE_FILE_MODAL_OPEN',
  CREATE_FILE_SUCCESS: 'CREATE_FILE_SUCCESS',
  EDIT_FILE_MODAL_OPEN: 'EDIT_FILE_MODAL_OPEN',
  EDIT_FILE_SUCCESS: 'EDIT_FILE_SUCCESS',
  DELETE_FILE_MODAL_OPEN: 'DELETE_FILE_MODAL_OPEN',
  DELETE_FILE_SUCCESS: 'DELETE_FILE_SUCCESS',
}