export default {
  REQUEST_USER_FILES: 'REQUEST_USER_FILES',
  UPLOAD_FILE_MODAL_OPEN: 'UPLOAD_FILE_MODAL_OPEN',
  UPLOAD_FILE_SUCCESS: 'UPLOAD_FILE_SUCCESS',
  EDIT_FILE_MODAL_OPEN: 'EDIT_FILE_MODAL_OPEN',
  EDIT_FILE_ON_CHANGE: 'EDIT_FILE_ON_CHANGE',
  EDIT_FILE_SUCCESS: 'EDIT_FILE_SUCCESS',
  DELETE_FILE_MODAL_OPEN: 'DELETE_FILE_MODAL_OPEN',
  DELETE_FILE_SUCCESS: 'DELETE_FILE_SUCCESS',
}